version: '2'
services:
  db_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sellioly_development
      MYSQL_USER: sellioly
      MYSQL_PASSWORD: sellioly
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - sellioly:/app
    ports:
      - "80:3000"
    depends_on:
      - db_mysql
    links:
      - db_mysql
    environment:
      DB_USER: root
      DB_NAME: sellioly_development
      DB_PASSWORD: root
      DB_HOST: db_mysql
volumes:
  sellioly:
    driver: local
  mysql_db_data_container:
    driver: local