# docker-compose.traefik.yml
services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    networks: [proxy]
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Point to a file that contains ONLY the token string
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/conf:/etc/traefik/dynamic:ro
      - ./traefik/letsencrypt:/letsencrypt
    secrets:
      - source: cf_token
        target: cf_token
        mode: 0400

secrets:
  cf_token:
    file: ./traefik/secrets/cf_token

networks:
  proxy:
    external: true
