services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    networks: [proxy]
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Use a PLAIN env var (this is what lego expects)
      - CF_DNS_API_TOKEN=HjrOOy6CkPAUAd75ns3jdyboeOurM5veJZ306_Dj
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/conf:/etc/traefik/dynamic:ro
      - ./traefik/letsencrypt:/letsencrypt
