user daemon;
daemon off;
master_process off;
worker_processes 1;
error_log stderr notice;
env redis;
env ruby_app;

events {
    worker_connections  1024;
}

http {

    mruby_init_worker_code '
        userdata = Userdata.new
        userdata.redis = Redis.new ENV["redis"], 6379
        # If your redis database is not 0, please select a correct one
        userdata.redis.select 1
      ';

    server {
        listen 80;
        server_name _;

        location / {
          proxy_set_header Host $host;
          proxy_pass   http://ruby_app:3000;

        }
    }

    server {
      listen 443 ssl;
      server_name _;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers HIGH:!aNULL:!MD5;
      ssl_certificate certs/cert.pem;
      ssl_certificate_key certs/key.pem;

      mruby_ssl_handshake_handler_code '
        ssl = Nginx::SSL.new
        domain = ssl.servername

        redis = Userdata.new.redis
        unless redis["#{domain}.crt"].nil? and redis["#{domain}.key"].nil?
          ssl.certificate_data = redis["#{domain}.crt"]
          ssl.certificate_key_data = redis["#{domain}.key"]
        end
      ';

        location / {
          proxy_set_header Host $host;
          proxy_pass   http://ruby_app:3000;

        }
    }
}
