development:
  adapter: async
  url: <%= ENV['REDIS_CABLE_URL'] %>
  channel_prefix: sellioly_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_CABLE_URL'] %>
  channel_prefix: sellioly_production
