upstream rails_backend {
  server app:3000;
  server app2:3000;
  server app3:3000;
  server app4:3000;
  server app5:3000;
  keepalive 32;
}

map $http_upgrade $connection_upgrade { default upgrade; "" close; }

server {
  listen 80;
  server_name shop.sellioly.com;

  # مسار تحدّي ACME
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  # أي شيء آخر → تحويل ل HTTPS (سنفعّله بعد إصدار الشهادة)
  location / {
    return 301 https://$host$request_uri;
  }
}
