version = 5.1.0
archive_dir = /etc/letsencrypt/archive/sellioly.com
cert = /etc/letsencrypt/live/sellioly.com/cert.pem
privkey = /etc/letsencrypt/live/sellioly.com/privkey.pem
chain = /etc/letsencrypt/live/sellioly.com/chain.pem
fullchain = /etc/letsencrypt/live/sellioly.com/fullchain.pem
[renewalparams]
account = de07e5a74f8a2d44d2cbf94c231b904c
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 60
dns_cloudflare_credentials = /cloudflare/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
