version = 5.1.0
archive_dir = /etc/letsencrypt/archive/shop.sellioly.com
cert = /etc/letsencrypt/live/shop.sellioly.com/cert.pem
privkey = /etc/letsencrypt/live/shop.sellioly.com/privkey.pem
chain = /etc/letsencrypt/live/shop.sellioly.com/chain.pem
fullchain = /etc/letsencrypt/live/shop.sellioly.com/fullchain.pem
[renewalparams]
account = de07e5a74f8a2d44d2cbf94c231b904c
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
shop.sellioly.com = /var/www/certbot
